import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { NotificationsProvider } from "@/lib/notifications";
import { BrandLoader } from "@/lib/brand-loader";
import { QueryProvider } from "@/lib/query-client";
import { RealtimeBridge } from "@/components/RealtimeBridge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* In a real app, derive tenantId from domain or session */}
        <ThemeProvider paletteName="Master">
          <QueryProvider>
            <BrandLoader />
            <RealtimeBridge />
            <NotificationsProvider>{children}</NotificationsProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
